In [61]:
from dotenv import load_dotenv
import os
from polygon import RESTClient
import json
import requests
import pydantic
import dataclasses
import inspect
import pandas as pd
import plotly.express as px
from datetime import datetime
import pytz
load_dotenv()
POLYGON_API_KEY = os.getenv("POLYGON_API_KEY")

In [2]:
client = RESTClient(POLYGON_API_KEY)

In [41]:
intl_daily_agg = client.get_daily_open_close_agg("AAPL","2025-09-03")

In [42]:
intl_daily_agg

DailyOpenCloseAgg(after_hours=238.1392, close=238.47, from_='2025-09-03', high=238.85, low=234.36, open=237.21, pre_market=235.85, status='OK', symbol='AAPL', volume=66427835.0, otc=None)

In [43]:
intl_daily_agg_5min = client.get_aggs("AAPL",5,"minute","2025-09-03","2025-09-03")

In [44]:
intl_daily_agg_5min

[Agg(open=235.85, high=235.85, low=235.43, close=235.78, volume=12828, vwap=235.6427, timestamp=1756886400000, transactions=602, otc=None),
 Agg(open=235.7, high=235.7, low=235.52, close=235.69, volume=8186, vwap=235.6329, timestamp=1756886700000, transactions=281, otc=None),
 Agg(open=235.62, high=235.9, low=235.62, close=235.88, volume=9313, vwap=235.7415, timestamp=1756887000000, transactions=314, otc=None),
 Agg(open=235.92, high=235.94, low=235.84, close=235.94, volume=4565, vwap=235.8871, timestamp=1756887300000, transactions=141, otc=None),
 Agg(open=236, high=236.2, low=235.99, close=236.15, volume=11075, vwap=236.0553, timestamp=1756887600000, transactions=365, otc=None),
 Agg(open=236.1, high=236.15, low=236.02, close=236.02, volume=3861, vwap=236.0964, timestamp=1756887900000, transactions=44, otc=None),
 Agg(open=236.04, high=236.15, low=236.03, close=236.04, volume=7382, vwap=236.0733, timestamp=1756888200000, transactions=145, otc=None),
 Agg(open=236.04, high=236.13, low=236.04, close=236.13, volume=3920, vwap=236.0976, timestamp=1756888500000, transactions=166, otc=None),
 Agg(open=236.2, high=236.2, low=236.13, close=236.2, volume=5076, vwap=236.1629, timestamp=1756888800000, transactions=103, otc=None),
 Agg(open=236.14, high=236.14, low=236.14, close=236.14, volume=175, vwap=236.1477, timestamp=1756889100000, transactions=10, otc=None),
 Agg(open=236.07, high=236.07, low=236.07, close=236.07, volume=1296, vwap=236.0774, timestamp=1756889400000, transactions=40, otc=None),
 Agg(open=236.08, high=236.2, low=236.08, close=236.2, volume=3003, vwap=236.1465, timestamp=1756889700000, transactions=90, otc=None),
 Agg(open=236.2, high=236.3, low=236.2, close=236.28, volume=1889, vwap=236.2479, timestamp=1756890000000, transactions=77, otc=None),
 Agg(open=236.2, high=236.3, low=236.15, close=236.25, volume=4816, vwap=236.2113, timestamp=1756890300000, transactions=168, otc=None),
 Agg(open=236.13, high=236.14, low=236.07, close=236.07, volume=2423, vwap=236.1053, timestamp=1756890600000, transactions=87, otc=None),
 Agg(open=236.07, high=236.1, low=236.07, close=236.07, volume=3356, vwap=236.0738, timestamp=1756890900000, transactions=59, otc=None),
 Agg(open=236.05, high=236.28, low=236.03, close=236.26, volume=3648, vwap=236.1505, timestamp=1756891200000, transactions=124, otc=None),
 Agg(open=236.26, high=236.3, low=236.26, close=236.3, volume=1770, vwap=236.2827, timestamp=1756891500000, transactions=51, otc=None),
 Agg(open=236.26, high=236.33, low=236.26, close=236.33, volume=2840, vwap=236.3011, timestamp=1756891800000, transactions=88, otc=None),
 Agg(open=236.3, high=236.4, low=236.3, close=236.38, volume=4095, vwap=236.3607, timestamp=1756892100000, transactions=138, otc=None),
 Agg(open=236.5, high=236.61, low=236.49, close=236.61, volume=7495, vwap=236.5312, timestamp=1756892400000, transactions=168, otc=None),
 Agg(open=236.65, high=236.78, low=236.65, close=236.7, volume=13678, vwap=236.7087, timestamp=1756892700000, transactions=246, otc=None),
 Agg(open=236.75, high=236.88, low=236.75, close=236.88, volume=6985, vwap=236.8038, timestamp=1756893000000, transactions=163, otc=None),
 Agg(open=236.89, high=237.2, low=236.81, close=237.06, volume=17256, vwap=237.0149, timestamp=1756893300000, transactions=516, otc=None),
 Agg(open=237.1, high=237.23, low=237, close=237.07, volume=7063, vwap=237.0853, timestamp=1756893600000, transactions=224, otc=None),
 Agg(open=237.11, high=237.15, low=237.08, close=237.15, volume=5001, vwap=237.1212, timestamp=1756893900000, transactions=183, otc=None),
 Agg(open=237.2, high=237.3, low=237.14, close=237.21, volume=12041, vwap=237.2432, timestamp=1756894200000, transactions=356, otc=None),
 Agg(open=237.23, high=237.27, low=237.14, close=237.27, volume=8635, vwap=237.241, timestamp=1756894500000, transactions=218, otc=None),
 Agg(open=237.18, high=237.34, low=237.15, close=237.34, volume=7631, vwap=237.2378, timestamp=1756894800000, transactions=234, otc=None),
 Agg(open=237.3, high=237.76, low=237.3, close=237.75, volume=11572, vwap=237.5664, timestamp=1756895100000, transactions=372, otc=None),
 Agg(open=237.63, high=237.78, low=237.52, close=237.58, volume=11590, vwap=237.6453, timestamp=1756895400000, transactions=246, otc=None),
 Agg(open=237.51, high=237.64, low=237.45, close=237.56, volume=6612, vwap=237.4928, timestamp=1756895700000, transactions=253, otc=None),
 Agg(open=237.5, high=237.57, low=237.3, close=237.3, volume=7744, vwap=237.4321, timestamp=1756896000000, transactions=171, otc=None),
 Agg(open=237.29, high=237.4, low=237, close=237.3, volume=9754, vwap=237.266, timestamp=1756896300000, transactions=252, otc=None),
 Agg(open=237.25, high=237.55, low=237.23, close=237.5, volume=21145, vwap=237.4062, timestamp=1756896600000, transactions=454, otc=None),
 Agg(open=237.69, high=237.97, low=237.6, close=237.64, volume=28609, vwap=237.7653, timestamp=1756896900000, transactions=545, otc=None),
 Agg(open=237.62, high=238.5, low=237.62, close=238.1, volume=38775, vwap=238.0247, timestamp=1756897200000, transactions=1001, otc=None),
 Agg(open=238.2, high=238.48, low=237.8, close=238.48, volume=26315, vwap=238.1291, timestamp=1756897500000, transactions=626, otc=None),
 Agg(open=238.26, high=239.18, low=238.26, close=238.83, volume=123725, vwap=238.8785, timestamp=1756897800000, transactions=1722, otc=None),
 Agg(open=238.82, high=239.13, low=238.73, close=238.73, volume=60866, vwap=238.8594, timestamp=1756898100000, transactions=978, otc=None),
 Agg(open=238.72, high=239.35, low=238.6, close=239.32, volume=46043, vwap=239.0348, timestamp=1756898400000, transactions=831, otc=None),
 Agg(open=239.34, high=239.4, low=238.75, close=238.75, volume=56231, vwap=239.0299, timestamp=1756898700000, transactions=884, otc=None),
 Agg(open=238.66, high=238.84, low=238.5, close=238.76, volume=48829, vwap=238.6426, timestamp=1756899000000, transactions=811, otc=None),
 Agg(open=238.75, high=238.94, low=238.62, close=238.73, volume=27447, vwap=238.78, timestamp=1756899300000, transactions=540, otc=None),
 Agg(open=238.68, high=238.8, low=238.61, close=238.8, volume=31637, vwap=238.7113, timestamp=1756899600000, transactions=569, otc=None),
 Agg(open=238.8, high=238.8, low=238.4, close=238.5, volume=30691, vwap=238.6365, timestamp=1756899900000, transactions=565, otc=None),
 Agg(open=238.5, high=238.53, low=238.26, close=238.32, volume=30808, vwap=238.4297, timestamp=1756900200000, transactions=309, otc=None),
 Agg(open=238.3, high=238.39, low=238.15, close=238.26, volume=33856, vwap=238.2705, timestamp=1756900500000, transactions=618, otc=None),
 Agg(open=237.7, high=239.4601, low=235.18, close=238.5117, volume=304813, vwap=238.0414, timestamp=1756900800000, transactions=4341, otc=None),
 Agg(open=238.54, high=238.54, low=238.051, close=238.14, volume=29593, vwap=238.2475, timestamp=1756901100000, transactions=560, otc=None),
 Agg(open=238.15, high=238.24, low=238.03, close=238.1001, volume=31521, vwap=238.1374, timestamp=1756901400000, transactions=496, otc=None),
 Agg(open=238.11, high=238.8, low=238, close=238.49, volume=63591, vwap=238.3549, timestamp=1756901700000, transactions=833, otc=None),
 Agg(open=238.5, high=238.5, low=238.0005, close=238.0005, volume=30886, vwap=238.303, timestamp=1756902000000, transactions=613, otc=None),
 Agg(open=238.1198, high=238.3, low=237.9, close=238.1512, volume=45949, vwap=238.0671, timestamp=1756902300000, transactions=752, otc=None),
 Agg(open=238.15, high=238.15, low=237.65, close=237.7118, volume=44342, vwap=237.8846, timestamp=1756902600000, transactions=864, otc=None),
 Agg(open=237.8, high=238, low=237.8, close=237.97, volume=19542, vwap=237.8999, timestamp=1756902900000, transactions=482, otc=None),
 Agg(open=237.84, high=238.29, low=237.84, close=238.1, volume=28403, vwap=238.0992, timestamp=1756903200000, transactions=660, otc=None),
 Agg(open=238.18, high=238.3, low=238, close=238.29, volume=27345, vwap=238.1902, timestamp=1756903500000, transactions=586, otc=None),
 Agg(open=238.251, high=238.3, low=238, close=238.01, volume=39473, vwap=238.133, timestamp=1756903800000, transactions=660, otc=None),
 Agg(open=238.0001, high=238.15, low=237.76, close=237.77, volume=34714, vwap=237.9357, timestamp=1756904100000, transactions=824, otc=None),
 Agg(open=237.86, high=238.3, low=237.7, close=238.29, volume=78062, vwap=237.9604, timestamp=1756904400000, transactions=1273, otc=None),
 Agg(open=238.27, high=238.75, low=238.1502, close=238.2514, volume=131465, vwap=238.4658, timestamp=1756904700000, transactions=1396, otc=None),
 Agg(open=238.2545, high=238.2991, low=237.6601, close=237.8, volume=46115, vwap=237.9372, timestamp=1756905000000, transactions=1050, otc=None),
 Agg(open=237.7, high=237.7615, low=237.26, close=237.4, volume=60088, vwap=237.5413, timestamp=1756905300000, transactions=1134, otc=None),
 Agg(open=237.41, high=237.79, low=237.19, close=237.24, volume=68559, vwap=237.434, timestamp=1756905600000, transactions=1251, otc=None),
 Agg(open=237.3, high=237.36, low=236.61, close=237.17, volume=230424, vwap=237.1284, timestamp=1756905900000, transactions=2050, otc=None),
 Agg(open=237.21, high=237.97, low=235.58, close=235.63, volume=4651299.0, vwap=236.8557, timestamp=1756906200000, transactions=56795, otc=None),
 Agg(open=235.62, high=235.96, low=234.9166, close=235.3, volume=1990477.0, vwap=235.3944, timestamp=1756906500000, transactions=29293, otc=None),
 Agg(open=235.29, high=235.43, low=234.49, close=234.505, volume=1446192.0, vwap=234.9687, timestamp=1756906800000, transactions=23639, otc=None),
 Agg(open=234.5, high=235.33, low=234.36, close=235.29, volume=1283559.0, vwap=234.8969, timestamp=1756907100000, transactions=21850, otc=None),
 Agg(open=235.29, high=236.48, low=235.22, close=236.39, volume=1617826.0, vwap=235.9812, timestamp=1756907400000, transactions=25259, otc=None),
 Agg(open=236.39, high=236.3958, low=235.23, close=235.69, volume=1338330.0, vwap=235.6398, timestamp=1756907700000, transactions=21539, otc=None),
 Agg(open=235.63, high=236.1, low=235.23, close=235.64, volume=1103192.0, vwap=235.6501, timestamp=1756908000000, transactions=21421, otc=None),
 Agg(open=235.67, high=236.1, low=235.45, close=235.6916, volume=976752, vwap=235.8019, timestamp=1756908300000, transactions=23063, otc=None),
 Agg(open=235.7, high=236.16, low=235.11, close=235.8, volume=1108964.0, vwap=235.6703, timestamp=1756908600000, transactions=19841, otc=None),
 Agg(open=235.78, high=237.06, low=235.78, close=236.995, volume=1295646.0, vwap=236.5146, timestamp=1756908900000, transactions=21423, otc=None),
 Agg(open=237.01, high=237.27, low=236.885, close=236.94, volume=1094613.0, vwap=237.0771, timestamp=1756909200000, transactions=21152, otc=None),
 Agg(open=236.95, high=237.2498, low=236.745, close=236.83, volume=1099807.0, vwap=237.0046, timestamp=1756909500000, transactions=19148, otc=None),
 Agg(open=236.8139, high=237.32, low=236.68, close=237.18, volume=983061, vwap=237.0958, timestamp=1756909800000, transactions=16895, otc=None),
 Agg(open=237.18, high=237.49, low=237.11, close=237.15, volume=977028, vwap=237.3147, timestamp=1756910100000, transactions=16917, otc=None),
 Agg(open=237.14, high=237.37, low=237.01, close=237.095, volume=668806, vwap=237.1789, timestamp=1756910400000, transactions=12810, otc=None),
 Agg(open=237.09, high=237.6, low=236.9201, close=237.47, volume=847248, vwap=237.2779, timestamp=1756910700000, transactions=21299, otc=None),
 Agg(open=237.485, high=237.52, low=236.85, close=236.99, volume=802010, vwap=237.1739, timestamp=1756911000000, transactions=21776, otc=None),
 Agg(open=236.99, high=237.1, low=236.8402, close=237, volume=594060, vwap=236.9585, timestamp=1756911300000, transactions=19602, otc=None),
 Agg(open=237.02, high=237.175, low=236.265, close=236.3, volume=726201, vwap=236.6281, timestamp=1756911600000, transactions=22823, otc=None),
 Agg(open=236.31, high=236.57, low=236.07, close=236.13, volume=674526, vwap=236.3057, timestamp=1756911900000, transactions=21406, otc=None),
 Agg(open=236.12, high=236.71, low=236.05, close=236.27, volume=615368, vwap=236.4396, timestamp=1756912200000, transactions=9056, otc=None),
 Agg(open=236.28, high=236.5458, low=236.1501, close=236.48, volume=448497, vwap=236.3652, timestamp=1756912500000, transactions=7266, otc=None),
 Agg(open=236.435, high=237.12, low=235.99, close=236.17, volume=452473, vwap=236.1654, timestamp=1756912800000, transactions=6680, otc=None),
 Agg(open=236.16, high=236.48, low=235.99, close=236.011, volume=496027, vwap=236.212, timestamp=1756913100000, transactions=6884, otc=None),
 Agg(open=236.02, high=236.125, low=235.66, close=236.0214, volume=588758, vwap=235.9265, timestamp=1756913400000, transactions=8046, otc=None),
 Agg(open=236.0358, high=236.33, low=235.93, close=236.25, volume=422847, vwap=236.126, timestamp=1756913700000, transactions=6574, otc=None),
 Agg(open=236.25, high=236.34, low=236.11, close=236.24, volume=430540, vwap=236.2462, timestamp=1756914000000, transactions=6074, otc=None),
 Agg(open=236.23, high=236.34, low=235.91, close=236.135, volume=302256, vwap=236.1404, timestamp=1756914300000, transactions=5314, otc=None),
 Agg(open=236.1384, high=236.35, low=235.97, close=236.02, volume=300102, vwap=236.1613, timestamp=1756914600000, transactions=4764, otc=None),
 Agg(open=236.01, high=236.02, low=235.49, close=235.615, volume=556878, vwap=235.7138, timestamp=1756914900000, transactions=5895, otc=None),
 Agg(open=235.61, high=235.785, low=235.52, close=235.6501, volume=288665, vwap=235.6514, timestamp=1756915200000, transactions=5033, otc=None),
 Agg(open=235.67, high=236.1142, low=235.6306, close=236, volume=527849, vwap=235.7696, timestamp=1756915500000, transactions=4533, otc=None),
 Agg(open=236.01, high=236.29, low=235.92, close=236.28, volume=443535, vwap=236.0797, timestamp=1756915800000, transactions=5488, otc=None),
 Agg(open=236.28, high=236.6, low=236.125, close=236.59, volume=323549, vwap=236.3278, timestamp=1756916100000, transactions=5041, otc=None),
 Agg(open=236.58, high=236.82, low=236.31, close=236.35, volume=333119, vwap=236.5754, timestamp=1756916400000, transactions=5298, otc=None),
 Agg(open=236.37, high=236.63, low=236.28, close=236.49, volume=311883, vwap=236.4916, timestamp=1756916700000, transactions=4608, otc=None),
 Agg(open=236.4998, high=236.75, low=236.44, close=236.75, volume=236945, vwap=236.6173, timestamp=1756917000000, transactions=4104, otc=None),
 Agg(open=236.745, high=236.98, low=236.66, close=236.94, volume=368235, vwap=236.8525, timestamp=1756917300000, transactions=5170, otc=None),
 Agg(open=236.94, high=237.1095, low=236.7, close=236.955, volume=416682, vwap=236.9465, timestamp=1756917600000, transactions=6262, otc=None),
 Agg(open=236.95, high=237.1699, low=236.7801, close=236.84, volume=338563, vwap=237.011, timestamp=1756917900000, transactions=5259, otc=None),
 Agg(open=236.84, high=237.17, low=236.72, close=237.15, volume=368050, vwap=236.9547, timestamp=1756918200000, transactions=5466, otc=None),
 Agg(open=237.155, high=237.35, low=237.05, close=237.055, volume=345160, vwap=237.2153, timestamp=1756918500000, transactions=5467, otc=None),
 Agg(open=237.055, high=237.47, low=236.99, close=237.42, volume=415310, vwap=237.2647, timestamp=1756918800000, transactions=5542, otc=None),
 Agg(open=237.415, high=237.6, low=237.34, close=237.58, volume=437668, vwap=237.4739, timestamp=1756919100000, transactions=6342, otc=None),
 Agg(open=237.5807, high=237.9, low=237.535, close=237.77, volume=594154, vwap=237.7647, timestamp=1756919400000, transactions=7568, otc=None),
 Agg(open=237.76, high=237.8385, low=237.555, close=237.6, volume=368258, vwap=237.6797, timestamp=1756919700000, transactions=5047, otc=None),
 Agg(open=237.595, high=237.68, low=237.38, close=237.6, volume=449179, vwap=237.55, timestamp=1756920000000, transactions=5330, otc=None),
 Agg(open=237.5899, high=237.59, low=237.34, close=237.4272, volume=314404, vwap=237.4724, timestamp=1756920300000, transactions=4451, otc=None),
 Agg(open=237.425, high=237.45, low=237.0601, close=237.1102, volume=371127, vwap=237.2579, timestamp=1756920600000, transactions=5741, otc=None),
 Agg(open=237.11, high=237.32, low=236.95, close=237.17, volume=479456, vwap=237.1272, timestamp=1756920900000, transactions=5440, otc=None),
 Agg(open=237.17, high=237.24, low=236.84, close=236.89, volume=342361, vwap=237.0252, timestamp=1756921200000, transactions=4940, otc=None),
 Agg(open=236.89, high=237.2716, low=236.63, close=237.26, volume=456908, vwap=236.9236, timestamp=1756921500000, transactions=5982, otc=None),
 Agg(open=237.28, high=237.39, low=237.04, close=237.05, volume=404016, vwap=237.238, timestamp=1756921800000, transactions=5175, otc=None),
 Agg(open=237.05, high=237.11, low=236.85, close=237.06, volume=314489, vwap=236.9993, timestamp=1756922100000, transactions=4266, otc=None),
 Agg(open=237.06, high=237.12, low=236.76, close=236.9301, volume=398124, vwap=236.9788, timestamp=1756922400000, transactions=5422, otc=None),
 Agg(open=236.93, high=237.04, low=236.7601, close=236.85, volume=315333, vwap=236.9071, timestamp=1756922700000, transactions=4392, otc=None),
 Agg(open=236.85, high=237.1, low=236.775, close=237.03, volume=302752, vwap=236.9106, timestamp=1756923000000, transactions=4462, otc=None),
 Agg(open=237.03, high=237.065, low=236.77, close=236.83, volume=308615, vwap=236.9072, timestamp=1756923300000, transactions=4451, otc=None),
 Agg(open=236.83, high=236.9401, low=236.76, close=236.84, volume=321092, vwap=236.8494, timestamp=1756923600000, transactions=4399, otc=None),
 Agg(open=236.835, high=236.97, low=236.7801, close=236.91, volume=330379, vwap=236.8707, timestamp=1756923900000, transactions=4308, otc=None),
 Agg(open=236.9, high=237.05, low=236.77, close=237.04, volume=337377, vwap=236.8971, timestamp=1756924200000, transactions=4761, otc=None),
 Agg(open=237.04, high=237.1, low=236.87, close=236.89, volume=409945, vwap=237.0023, timestamp=1756924500000, transactions=5207, otc=None),
 Agg(open=236.9, high=237.25, low=236.775, close=237.18, volume=407005, vwap=237.0041, timestamp=1756924800000, transactions=5047, otc=None),
 Agg(open=237.175, high=237.27, low=236.9042, close=236.92, volume=368448, vwap=237.0943, timestamp=1756925100000, transactions=4830, otc=None),
 Agg(open=236.9301, high=237, low=236.7916, close=236.805, volume=280611, vwap=236.8967, timestamp=1756925400000, transactions=4176, otc=None),
 Agg(open=236.805, high=236.96, low=236.79, close=236.9414, volume=281916, vwap=236.8867, timestamp=1756925700000, transactions=4065, otc=None),
 Agg(open=236.94, high=237.3, low=236.8, close=237.26, volume=463935, vwap=237.1054, timestamp=1756926000000, transactions=5847, otc=None),
 Agg(open=237.27, high=237.4, low=237.09, close=237.095, volume=501301, vwap=237.2383, timestamp=1756926300000, transactions=6278, otc=None),
 Agg(open=237.085, high=237.2, low=236.96, close=237.09, volume=403899, vwap=237.0721, timestamp=1756926600000, transactions=4645, otc=None),
 Agg(open=237.08, high=237.23, low=236.89, close=237.225, volume=408000, vwap=237.0342, timestamp=1756926900000, transactions=5359, otc=None),
 Agg(open=237.22, high=237.32, low=237.0587, close=237.247, volume=419667, vwap=237.1766, timestamp=1756927200000, transactions=5499, otc=None),
 Agg(open=237.255, high=237.45, low=237.14, close=237.155, volume=550239, vwap=237.3325, timestamp=1756927500000, transactions=6797, otc=None),
 Agg(open=237.16, high=237.44, low=237.15, close=237.44, volume=455326, vwap=237.3447, timestamp=1756927800000, transactions=6332, otc=None),
 Agg(open=237.445, high=237.66, low=237.43, close=237.53, volume=729799, vwap=237.5514, timestamp=1756928100000, transactions=8492, otc=None),
 Agg(open=237.53, high=237.8, low=237.53, close=237.695, volume=656600, vwap=237.6748, timestamp=1756928400000, transactions=8940, otc=None),

In [45]:
type(intl_daily_agg_5min[0])

polygon.rest.models.aggs.Agg

In [46]:
agg = intl_daily_agg_5min[0]
print(dataclasses.is_dataclass(agg))
print(getattr(agg,"__slots__",None))
print([n for n in dir(agg) if not n.startswith("_")])
dataclasses.asdict(agg)

True
None
['close', 'from_dict', 'high', 'low', 'open', 'otc', 'timestamp', 'transactions', 'volume', 'vwap']

{'open': 235.85,
 'high': 235.85,
 'low': 235.43,
 'close': 235.78,
 'volume': 12828,
 'vwap': 235.6427,
 'timestamp': 1756886400000,
 'transactions': 602,
 'otc': None}

In [47]:
intl_daily_agg_5min_dicts = [dataclasses.asdict(agg) for agg in intl_daily_agg_5min]
intl_daily_agg_5min_dicts

[{'open': 235.85,
  'high': 235.85,
  'low': 235.43,
  'close': 235.78,
  'volume': 12828,
  'vwap': 235.6427,
  'timestamp': 1756886400000,
  'transactions': 602,
  'otc': None},
 {'open': 235.7,
  'high': 235.7,
  'low': 235.52,
  'close': 235.69,
  'volume': 8186,
  'vwap': 235.6329,
  'timestamp': 1756886700000,
  'transactions': 281,
  'otc': None},
 {'open': 235.62,
  'high': 235.9,
  'low': 235.62,
  'close': 235.88,
  'volume': 9313,
  'vwap': 235.7415,
  'timestamp': 1756887000000,
  'transactions': 314,
  'otc': None},
 {'open': 235.92,
  'high': 235.94,
  'low': 235.84,
  'close': 235.94,
  'volume': 4565,
  'vwap': 235.8871,
  'timestamp': 1756887300000,
  'transactions': 141,
  'otc': None},
 {'open': 236,
  'high': 236.2,
  'low': 235.99,
  'close': 236.15,
  'volume': 11075,
  'vwap': 236.0553,
  'timestamp': 1756887600000,
  'transactions': 365,
  'otc': None},
 {'open': 236.1,
  'high': 236.15,
  'low': 236.02,
  'close': 236.02,
  'volume': 3861,
  'vwap': 236.0964,
  'timestamp': 1756887900000,
  'transactions': 44,
  'otc': None},
 {'open': 236.04,
  'high': 236.15,
  'low': 236.03,
  'close': 236.04,
  'volume': 7382,
  'vwap': 236.0733,
  'timestamp': 1756888200000,
  'transactions': 145,
  'otc': None},
 {'open': 236.04,
  'high': 236.13,
  'low': 236.04,
  'close': 236.13,
  'volume': 3920,
  'vwap': 236.0976,
  'timestamp': 1756888500000,
  'transactions': 166,
  'otc': None},
 {'open': 236.2,
  'high': 236.2,
  'low': 236.13,
  'close': 236.2,
  'volume': 5076,
  'vwap': 236.1629,
  'timestamp': 1756888800000,
  'transactions': 103,
  'otc': None},
 {'open': 236.14,
  'high': 236.14,
  'low': 236.14,
  'close': 236.14,
  'volume': 175,
  'vwap': 236.1477,
  'timestamp': 1756889100000,
  'transactions': 10,
  'otc': None},
 {'open': 236.07,
  'high': 236.07,
  'low': 236.07,
  'close': 236.07,
  'volume': 1296,
  'vwap': 236.0774,
  'timestamp': 1756889400000,
  'transactions': 40,
  'otc': None},
 {'open': 236.08,
  'high': 236.2,
  'low': 236.08,
  'close': 236.2,
  'volume': 3003,
  'vwap': 236.1465,
  'timestamp': 1756889700000,
  'transactions': 90,
  'otc': None},
 {'open': 236.2,
  'high': 236.3,
  'low': 236.2,
  'close': 236.28,
  'volume': 1889,
  'vwap': 236.2479,
  'timestamp': 1756890000000,
  'transactions': 77,
  'otc': None},
 {'open': 236.2,
  'high': 236.3,
  'low': 236.15,
  'close': 236.25,
  'volume': 4816,
  'vwap': 236.2113,
  'timestamp': 1756890300000,
  'transactions': 168,
  'otc': None},
 {'open': 236.13,
  'high': 236.14,
  'low': 236.07,
  'close': 236.07,
  'volume': 2423,
  'vwap': 236.1053,
  'timestamp': 1756890600000,
  'transactions': 87,
  'otc': None},
 {'open': 236.07,
  'high': 236.1,
  'low': 236.07,
  'close': 236.07,
  'volume': 3356,
  'vwap': 236.0738,
  'timestamp': 1756890900000,
  'transactions': 59,
  'otc': None},
 {'open': 236.05,
  'high': 236.28,
  'low': 236.03,
  'close': 236.26,
  'volume': 3648,
  'vwap': 236.1505,
  'timestamp': 1756891200000,
  'transactions': 124,
  'otc': None},
 {'open': 236.26,
  'high': 236.3,
  'low': 236.26,
  'close': 236.3,
  'volume': 1770,
  'vwap': 236.2827,
  'timestamp': 1756891500000,
  'transactions': 51,
  'otc': None},
 {'open': 236.26,
  'high': 236.33,
  'low': 236.26,
  'close': 236.33,
  'volume': 2840,
  'vwap': 236.3011,
  'timestamp': 1756891800000,
  'transactions': 88,
  'otc': None},
 {'open': 236.3,
  'high': 236.4,
  'low': 236.3,
  'close': 236.38,
  'volume': 4095,
  'vwap': 236.3607,
  'timestamp': 1756892100000,
  'transactions': 138,
  'otc': None},
 {'open': 236.5,
  'high': 236.61,
  'low': 236.49,
  'close': 236.61,
  'volume': 7495,
  'vwap': 236.5312,
  'timestamp': 1756892400000,
  'transactions': 168,
  'otc': None},
 {'open': 236.65,
  'high': 236.78,
  'low': 236.65,
  'close': 236.7,
  'volume': 13678,
  'vwap': 236.7087,
  'timestamp': 1756892700000,
  'transactions': 246,
  'otc': None},
 {'open': 236.75,
  'high': 236.88,
  'low': 236.75,
  'close': 236.88,
  'volume': 6985,
  'vwap': 236.8038,
  'timestamp': 1756893000000,
  'transactions': 163,
  'otc': None},
 {'open': 236.89,
  'high': 237.2,
  'low': 236.81,
  'close': 237.06,
  'volume': 17256,
  'vwap': 237.0149,
  'timestamp': 1756893300000,
  'transactions': 516,
  'otc': None},
 {'open': 237.1,
  'high': 237.23,
  'low': 237,
  'close': 237.07,
  'volume': 7063,
  'vwap': 237.0853,
  'timestamp': 1756893600000,
  'transactions': 224,
  'otc': None},
 {'open': 237.11,
  'high': 237.15,
  'low': 237.08,
  'close': 237.15,
  'volume': 5001,
  'vwap': 237.1212,
  'timestamp': 1756893900000,
  'transactions': 183,
  'otc': None},
 {'open': 237.2,
  'high': 237.3,
  'low': 237.14,
  'close': 237.21,
  'volume': 12041,
  'vwap': 237.2432,
  'timestamp': 1756894200000,
  'transactions': 356,
  'otc': None},
 {'open': 237.23,
  'high': 237.27,
  'low': 237.14,
  'close': 237.27,
  'volume': 8635,
  'vwap': 237.241,
  'timestamp': 1756894500000,
  'transactions': 218,
  'otc': None},
 {'open': 237.18,
  'high': 237.34,
  'low': 237.15,
  'close': 237.34,
  'volume': 7631,
  'vwap': 237.2378,
  'timestamp': 1756894800000,
  'transactions': 234,
  'otc': None},
 {'open': 237.3,
  'high': 237.76,
  'low': 237.3,
  'close': 237.75,
  'volume': 11572,
  'vwap': 237.5664,
  'timestamp': 1756895100000,
  'transactions': 372,
  'otc': None},
 {'open': 237.63,
  'high': 237.78,
  'low': 237.52,
  'close': 237.58,
  'volume': 11590,
  'vwap': 237.6453,
  'timestamp': 1756895400000,
  'transactions': 246,
  'otc': None},
 {'open': 237.51,
  'high': 237.64,
  'low': 237.45,
  'close': 237.56,
  'volume': 6612,
  'vwap': 237.4928,
  'timestamp': 1756895700000,
  'transactions': 253,
  'otc': None},
 {'open': 237.5,
  'high': 237.57,
  'low': 237.3,
  'close': 237.3,
  'volume': 7744,
  'vwap': 237.4321,
  'timestamp': 1756896000000,
  'transactions': 171,
  'otc': None},
 {'open': 237.29,
  'high': 237.4,
  'low': 237,
  'close': 237.3,
  'volume': 9754,
  'vwap': 237.266,
  'timestamp': 1756896300000,
  'transactions': 252,
  'otc': None},
 {'open': 237.25,
  'high': 237.55,
  'low': 237.23,
  'close': 237.5,
  'volume': 21145,
  'vwap': 237.4062,
  'timestamp': 1756896600000,
  'transactions': 454,
  'otc': None},
 {'open': 237.69,
  'high': 237.97,
  'low': 237.6,
  'close': 237.64,
  'volume': 28609,
  'vwap': 237.7653,
  'timestamp': 1756896900000,
  'transactions': 545,
  'otc': None},
 {'open': 237.62,
  'high': 238.5,
  'low': 237.62,
  'close': 238.1,
  'volume': 38775,
  'vwap': 238.0247,
  'timestamp': 1756897200000,
  'transactions': 1001,
  'otc': None},
 {'open': 238.2,
  'high': 238.48,
  'low': 237.8,
  'close': 238.48,
  'volume': 26315,
  'vwap': 238.1291,
  'timestamp': 1756897500000,
  'transactions': 626,
  'otc': None},
 {'open': 238.26,
  'high': 239.18,
  'low': 238.26,
  'close': 238.83,
  'volume': 123725,
  'vwap': 238.8785,
  'timestamp': 1756897800000,
  'transactions': 1722,
  'otc': None},
 {'open': 238.82,
  'high': 239.13,
  'low': 238.73,
  'close': 238.73,
  'volume': 60866,
  'vwap': 238.8594,
  'timestamp': 1756898100000,
  'transactions': 978,
  'otc': None},
 {'open': 238.72,
  'high': 239.35,
  'low': 238.6,
  'close': 239.32,
  'volume': 46043,
  'vwap': 239.0348,
  'timestamp': 1756898400000,
  'transactions': 831,
  'otc': None},
 {'open': 239.34,
  'high': 239.4,
  'low': 238.75,
  'close': 238.75,
  'volume': 56231,
  'vwap': 239.0299,
  'timestamp': 1756898700000,
  'transactions': 884,
  'otc': None},
 {'open': 238.66,
  'high': 238.84,
  'low': 238.5,
  'close': 238.76,
  'volume': 48829,
  'vwap': 238.6426,
  'timestamp': 1756899000000,
  'transactions': 811,
  'otc': None},
 {'open': 238.75,
  'high': 238.94,
  'low': 238.62,
  'close': 238.73,
  'volume': 27447,
  'vwap': 238.78,
  'timestamp': 1756899300000,
  'transactions': 540,
  'otc': None},
 {'open': 238.68,
  'high': 238.8,
  'low': 238.61,
  'close': 238.8,
  'volume': 31637,
  'vwap': 238.7113,
  'timestamp': 1756899600000,
  'transactions': 569,
  'otc': None},
 {'open': 238.8,
  'high': 238.8,
  'low': 238.4,
  'close': 238.5,
  'volume': 30691,
  'vwap': 238.6365,
  'timestamp': 1756899900000,
  'transactions': 565,
  'otc': None},
 {'open': 238.5,
  'high': 238.53,
  'low': 238.26,
  'close': 238.32,
  'volume': 30808,
  'vwap': 238.4297,
  'timestamp': 1756900200000,
  'transactions': 309,
  'otc': None},
 {'open': 238.3,
  'high': 238.39,
  'low': 238.15,
  'close': 238.26,
  'volume': 33856,
  'vwap': 238.2705,
  'timestamp': 1756900500000,
  'transactions': 618,
  'otc': None},
 {'open': 237.7,
  'high': 239.4601,
  'low': 235.18,
  'close': 238.5117,
  'volume': 304813,
  'vwap': 238.0414,
  'timestamp': 1756900800000,
  'transactions': 4341,
  'otc': None},
 {'open': 238.54,
  'high': 238.54,
  'low': 238.051,
  'close': 238.14,
  'volume': 29593,
  'vwap': 238.2475,
  'timestamp': 1756901100000,
  'transactions': 560,
  'otc': None},
 {'open': 238.15,
  'high': 238.24,
  'low': 238.03,
  'close': 238.1001,
  'volume': 31521,
  'vwap': 238.1374,
  'timestamp': 1756901400000,
  'transactions': 496,
  'otc': None},
 {'open': 238.11,
  'high': 238.8,
  'low': 238,
  'close': 238.49,
  'volume': 63591,
  'vwap': 238.3549,
  'timestamp': 1756901700000,
  'transactions': 833,
  'otc': None},
 {'open': 238.5,
  'high': 238.5,
  'low': 238.0005,
  'close': 238.0005,
  'volume': 30886,
  'vwap': 238.303,
  'timestamp': 1756902000000,
  'transactions': 613,
  'otc': None},
 {'open': 238.1198,
  'high': 238.3,
  'low': 237.9,
  'close': 238.1512,
  'volume': 45949,
  'vwap': 238.0671,
  'timestamp': 1756902300000,
  'transactions': 752,
  'otc': None},
 {'open': 238.15,
  'high': 238.15,
  'low': 237.65,
  'close': 237.7118,
  'volume': 44342,
  'vwap': 237.8846,
  'timestamp': 1756902600000,
  'transactions': 864,
  'otc': None},
 {'open': 237.8,
  'high': 238,
  'low': 237.8,
  'close': 237.97,
  'volume': 19542,
  'vwap': 237.8999,
  'timestamp': 1756902900000,
  'transactions': 482,
  'otc': None},
 {'open': 237.84,
  'high': 238.29,
  'low': 237.84,
  'close': 238.1,
  'volume': 28403,
  'vwap': 238.0992,
  'timestamp': 1756903200000,
  'transactions': 660,
  'otc': None},
 {'open': 238.18,
  'high': 238.3,
  'low': 238,
  'close': 238.29,
  'volume': 27345,
  'vwap': 238.1902,
  'timestamp': 1756903500000,
  'transactions': 586,
  'otc': None},
 {'open': 238.251,
  'high': 238.3,
  'low': 238,
  'close': 238.01,
  'volume': 39473,
  'vwap': 238.133,
  'timestamp': 1756903800000,
  'transactions': 660,
  'otc': None},
 {'open': 238.0001,
  'high': 238.15,
  'low': 237.76,
  'close': 237.77,
  'volume': 34714,
  'vwap': 237.9357,
  'timestamp': 1756904100000,
  'transactions': 824,
  'otc': None},
 {'open': 237.86,
  'high': 238.3,
  'low': 237.7,
  'close': 238.29,
  'volume': 78062,
  'vwap': 237.9604,
  'timestamp': 1756904400000,
  'transactions': 1273,
  'otc': None},
 {'open': 238.27,
  'high': 238.75,
  'low': 238.1502,
  'close': 238.2514,
  'volume': 131465,
  'vwap': 238.4658,
  'timestamp': 1756904700000,
  'transactions': 1396,
  'otc': None},
 {'open': 238.2545,
  'high': 238.2991,
  'low': 237.6601,
  'close': 237.8,
  'volume': 46115,
  'vwap': 237.9372,
  'timestamp': 1756905000000,
  'transactions': 1050,
  'otc': None},
 {'open': 237.7,
  'high': 237.7615,
  'low': 237.26,
  'close': 237.4,
  'volume': 60088,
  'vwap': 237.5413,
  'timestamp': 1756905300000,
  'transactions': 1134,
  'otc': None},
 {'open': 237.41,
  'high': 237.79,
  'low': 237.19,
  'close': 237.24,
  'volume': 68559,
  'vwap': 237.434,
  'timestamp': 1756905600000,
  'transactions': 1251,
  'otc': None},
 {'open': 237.3,
  'high': 237.36,
  'low': 236.61,
  'close': 237.17,
  'volume': 230424,
  'vwap': 237.1284,
  'timestamp': 1756905900000,
  'transactions': 2050,
  'otc': None},
 {'open': 237.21,
  'high': 237.97,
  'low': 235.58,
  'close': 235.63,
  'volume': 4651299.0,
  'vwap': 236.8557,
  'timestamp': 1756906200000,
  'transactions': 56795,
  'otc': None},
 {'open': 235.62,
  'high': 235.96,
  'low': 234.9166,
  'close': 235.3,
  'volume': 1990477.0,
  'vwap': 235.3944,
  'timestamp': 1756906500000,
  'transactions': 29293,
  'otc': None},
 {'open': 235.29,
  'high': 235.43,
  'low': 234.49,
  'close': 234.505,
  'volume': 1446192.0,
  'vwap': 234.9687,
  'timestamp': 1756906800000,
  'transactions': 23639,
  'otc': None},
 {'open': 234.5,
  'high': 235.33,
  'low': 234.36,
  'close': 235.29,
  'volume': 1283559.0,
  'vwap': 234.8969,
  'timestamp': 1756907100000,
  'transactions': 21850,
  'otc': None},
 {'open': 235.29,
  'high': 236.48,
  'low': 235.22,
  'close': 236.39,
  'volume': 1617826.0,
  'vwap': 235.9812,
  'timestamp': 1756907400000,
  'transactions': 25259,
  'otc': None},
 {'open': 236.39,
  'high': 236.3958,
  'low': 235.23,
  'close': 235.69,
  'volume': 1338330.0,
  'vwap': 235.6398,
  'timestamp': 1756907700000,
  'transactions': 21539,
  'otc': None},
 {'open': 235.63,
  'high': 236.1,
  'low': 235.23,
  'close': 235.64,
  'volume': 1103192.0,
  'vwap': 235.6501,
  'timestamp': 1756908000000,
  'transactions': 21421,
  'otc': None},
 {'open': 235.67,
  'high': 236.1,
  'low': 235.45,
  'close': 235.6916,
  'volume': 976752,
  'vwap': 235.8019,
  'timestamp': 1756908300000,
  'transactions': 23063,
  'otc': None},
 {'open': 235.7,
  'high': 236.16,
  'low': 235.11,
  'close': 235.8,
  'volume': 1108964.0,
  'vwap': 235.6703,
  'timestamp': 1756908600000,
  'transactions': 19841,
  'otc': None},
 {'open': 235.78,
  'high': 237.06,
  'low': 235.78,
  'close': 236.995,
  'volume': 1295646.0,
  'vwap': 236.5146,
  'timestamp': 1756908900000,
  'transactions': 21423,
  'otc': None},
 {'open': 237.01,
  'high': 237.27,
  'low': 236.885,
  'close': 236.94,
  'volume': 1094613.0,
  'vwap': 237.0771,
  'timestamp': 1756909200000,
  'transactions': 21152,
  'otc': None},
 {'open': 236.95,
  'high': 237.2498,
  'low': 236.745,
  'close': 236.83,
  'volume': 1099807.0,
  'vwap': 237.0046,
  'timestamp': 1756909500000,
  'transactions': 19148,
  'otc': None},
 {'open': 236.8139,
  'high': 237.32,
  'low': 236.68,
  'close': 237.18,
  'volume': 983061,
  'vwap': 237.0958,
  'timestamp': 1756909800000,
  'transactions': 16895,
  'otc': None},
 {'open': 237.18,
  'high': 237.49,
  'low': 237.11,
  'close': 237.15,
  'volume': 977028,
  'vwap': 237.3147,
  'timestamp': 1756910100000,
  'transactions': 16917,
  'otc': None},
 {'open': 237.14,
  'high': 237.37,
  'low': 237.01,
  'close': 237.095,
  'volume': 668806,
  'vwap': 237.1789,
  'timestamp': 1756910400000,
  'transactions': 12810,
  'otc': None},
 {'open': 237.09,
  'high': 237.6,
  'low': 236.9201,
  'close': 237.47,
  'volume': 847248,
  'vwap': 237.2779,
  'timestamp': 1756910700000,
  'transactions': 21299,
  'otc': None},
 {'open': 237.485,
  'high': 237.52,
  'low': 236.85,
  'close': 236.99,
  'volume': 802010,
  'vwap': 237.1739,
  'timestamp': 1756911000000,
  'transactions': 21776,
  'otc': None},
 {'open': 236.99,
  'high': 237.1,
  'low': 236.8402,
  'close': 237,
  'volume': 594060,
  'vwap': 236.9585,
  'timestamp': 1756911300000,
  'transactions': 19602,
  'otc': None},
 {'open': 237.02,
  'high': 237.175,
  'low': 236.265,
  'close': 236.3,
  'volume': 726201,
  'vwap': 236.6281,
  'timestamp': 1756911600000,
  'transactions': 22823,
  'otc': None},
 {'open': 236.31,
  'high': 236.57,
  'low': 236.07,
  'close': 236.13,
  'volume': 674526,
  'vwap': 236.3057,
  'timestamp': 1756911900000,
  'transactions': 21406,
  'otc': None},
 {'open': 236.12,
  'high': 236.71,
  'low': 236.05,
  'close': 236.27,
  'volume': 615368,
  'vwap': 236.4396,
  'timestamp': 1756912200000,
  'transactions': 9056,
  'otc': None},
 {'open': 236.28,
  'high': 236.5458,
  'low': 236.1501,
  'close': 236.48,
  'volume': 448497,
  'vwap': 236.3652,
  'timestamp': 1756912500000,
  'transactions': 7266,
  'otc': None},
 {'open': 236.435,
  'high': 237.12,
  'low': 235.99,
  'close': 236.17,
  'volume': 452473,
  'vwap': 236.1654,
  'timestamp': 1756912800000,
  'transactions': 6680,
  'otc': None},
 {'open': 236.16,
  'high': 236.48,
  'low': 235.99,
  'close': 236.011,
  'volume': 496027,
  'vwap': 236.212,
  'timestamp': 1756913100000,
  'transactions': 6884,
  'otc': None},
 {'open': 236.02,
  'high': 236.125,
  'low': 235.66,
  'close': 236.0214,
  'volume': 588758,
  'vwap': 235.9265,
  'timestamp': 1756913400000,
  'transactions': 8046,
  'otc': None},
 {'open': 236.0358,
  'high': 236.33,
  'low': 235.93,
  'close': 236.25,
  'volume': 422847,
  'vwap': 236.126,
  'timestamp': 1756913700000,
  'transactions': 6574,
  'otc': None},
 {'open': 236.25,
  'high': 236.34,
  'low': 236.11,
  'close': 236.24,
  'volume': 430540,
  'vwap': 236.2462,
  'timestamp': 1756914000000,
  'transactions': 6074,
  'otc': None},
 {'open': 236.23,
  'high': 236.34,
  'low': 235.91,
  'close': 236.135,
  'volume': 302256,
  'vwap': 236.1404,
  'timestamp': 1756914300000,
  'transactions': 5314,
  'otc': None},
 {'open': 236.1384,
  'high': 236.35,
  'low': 235.97,
  'close': 236.02,
  'volume': 300102,
  'vwap': 236.1613,
  'timestamp': 1756914600000,
  'transactions': 4764,
  'otc': None},
 {'open': 236.01,
  'high': 236.02,
  'low': 235.49,
  'close': 235.615,
  'volume': 556878,
  'vwap': 235.7138,
  'timestamp': 1756914900000,
  'transactions': 5895,
  'otc': None},
 {'open': 235.61,
  'high': 235.785,
  'low': 235.52,
  'close': 235.6501,
  'volume': 288665,
  'vwap': 235.6514,
  'timestamp': 1756915200000,
  'transactions': 5033,
  'otc': None},
 {'open': 235.67,
  'high': 236.1142,
  'low': 235.6306,
  'close': 236,
  'volume': 527849,
  'vwap': 235.7696,
  'timestamp': 1756915500000,
  'transactions': 4533,
  'otc': None},
 {'open': 236.01,
  'high': 236.29,
  'low': 235.92,
  'close': 236.28,
  'volume': 443535,
  'vwap': 236.0797,
  'timestamp': 1756915800000,
  'transactions': 5488,
  'otc': None},
 {'open': 236.28,
  'high': 236.6,
  'low': 236.125,
  'close': 236.59,
  'volume': 323549,
  'vwap': 236.3278,
  'timestamp': 1756916100000,
  'transactions': 5041,
  'otc': None},
 {'open': 236.58,
  'high': 236.82,
  'low': 236.31,
  'close': 236.35,
  'volume': 333119,
  'vwap': 236.5754,
  'timestamp': 1756916400000,
  'transactions': 5298,
  'otc': None},
 {'open': 236.37,
  'high': 236.63,
  'low': 236.28,
  'close': 236.49,
  'volume': 311883,
  'vwap': 236.4916,
  'timestamp': 1756916700000,
  'transactions': 4608,
  'otc': None},
 {'open': 236.4998,
  'high': 236.75,
  'low': 236.44,
  'close': 236.75,
  'volume': 236945,
  'vwap': 236.6173,
  'timestamp': 1756917000000,
  'transactions': 4104,
  'otc': None},
 {'open': 236.745,
  'high': 236.98,
  'low': 236.66,
  'close': 236.94,
  'volume': 368235,
  'vwap': 236.8525,
  'timestamp': 1756917300000,
  'transactions': 5170,
  'otc': None},
 {'open': 236.94,
  'high': 237.1095,
  'low': 236.7,
  'close': 236.955,
  'volume': 416682,
  'vwap': 236.9465,
  'timestamp': 1756917600000,
  'transactions': 6262,
  'otc': None},
 {'open': 236.95,
  'high': 237.1699,
  'low': 236.7801,
  'close': 236.84,
  'volume': 338563,
  'vwap': 237.011,
  'timestamp': 1756917900000,
  'transactions': 5259,
  'otc': None},
 {'open': 236.84,
  'high': 237.17,
  'low': 236.72,
  'close': 237.15,
  'volume': 368050,
  'vwap': 236.9547,
  'timestamp': 1756918200000,
  'transactions': 5466,
  'otc': None},
 {'open': 237.155,
  'high': 237.35,
  'low': 237.05,
  'close': 237.055,
  'volume': 345160,
  'vwap': 237.2153,
  'timestamp': 1756918500000,
  'transactions': 5467,
  'otc': None},
 {'open': 237.055,
  'high': 237.47,
  'low': 236.99,
  'close': 237.42,
  'volume': 415310,
  'vwap': 237.2647,
  'timestamp': 1756918800000,
  'transactions': 5542,
  'otc': None},
 {'open': 237.415,
  'high': 237.6,
  'low': 237.34,
  'close': 237.58,
  'volume': 437668,
  'vwap': 237.4739,
  'timestamp': 1756919100000,
  'transactions': 6342,
  'otc': None},
 {'open': 237.5807,
  'high': 237.9,
  'low': 237.535,
  'close': 237.77,
  'volume': 594154,

In [48]:
df = pd.DataFrame(intl_daily_agg_5min_dicts)
df["timestamp_utc"] = pd.to_datetime(df["timestamp"],unit="ms",utc=True)
df["timestamp_et"] = df["timestamp_utc"].dt.tz_convert("America/New_York")
df

,open,high,low,close,volume,vwap,timestamp,transactions,otc,timestamp_utc,timestamp_et
0,235.85,235.8500,235.4300,235.7800,12828.0,235.6427,1756886400000,602,None,2025-09-03 08:00:00+00:00,2025-09-03 04:00:00-04:00
1,235.70,235.7000,235.5200,235.6900,8186.0,235.6329,1756886700000,281,None,2025-09-03 08:05:00+00:00,2025-09-03 04:05:00-04:00
2,235.62,235.9000,235.6200,235.8800,9313.0,235.7415,1756887000000,314,None,2025-09-03 08:10:00+00:00,2025-09-03 04:10:00-04:00
3,235.92,235.9400,235.8400,235.9400,4565.0,235.8871,1756887300000,141,None,2025-09-03 08:15:00+00:00,2025-09-03 04:15:00-04:00
4,236.00,236.2000,235.9900,236.1500,11075.0,236.0553,1756887600000,365,None,2025-09-03 08:20:00+00:00,2025-09-03 04:20:00-04:00
...,...,...,...,...,...,...,...,...,...,...,...
187,238.06,238.0700,238.0600,238.0606,1134.0,238.0649,1756942500000,50,None,2025-09-03 23:35:00+00:00,2025-09-03 19:35:00-04:00
188,238.14,238.1400,237.9900,238.0000,5897.0,238.0513,1756942800000,81,None,2025-09-03 23:40:00+00:00,2025-09-03 19:40:00-04:00
189,238.00,238.0800,237.9106,238.0800,5071.0,238.0082,1756943100000,83,None,2025-09-03 23:45:00+00:00,2025-09-03 19:45:00-04:00
190,238.06,238.1600,238.0600,238.0600,4883.0,238.1117,1756943400000,68,None,2025-09-03 23:50:00+00:00,2025-09-03 19:50:00-04:00
191,238.16,238.1786,238.0000,238.1392,6927.0,238.0985,1756943700000,90,None,2025-09-03 23:55:00+00:00,2025-09-03 19:55:00-04:00

In [63]:
#PUlling 5 min aggregates for a 15 minute window
est = pytz.timezone("US/Eastern")
window_start = est.localize(datetime.strptime('2025-09-03 09:00:00',"%Y-%m-%d %H:%M:%S"))
window_end = est.localize(datetime.strptime('2025-09-03 09:15:00',"%Y-%m-%d %H:%M:%S"))
intl_5min_agg_over_15_mins = client.get_aggs("AAPL",5,"minute",window_start,window_end)
intl_5min_agg_over_15_mins_dict = [dataclasses.asdict(agg) for agg in intl_5min_agg_over_15_mins]
df15 = pd.DataFrame(intl_5min_agg_over_15_mins_dict)
df15["timestamp_utc"] = pd.to_datetime(df15["timestamp"],unit="ms",utc=True)
df15["timestamp_et"] = df15["timestamp_utc"].dt.tz_convert("America/New_York")
df15

,open,high,low,close,volume,vwap,timestamp,transactions,otc,timestamp_utc,timestamp_et
0,237.8600,238.3000,237.7000,238.2900,78062,237.9604,1756904400000,1273,None,2025-09-03 13:00:00+00:00,2025-09-03 09:00:00-04:00
1,238.2700,238.7500,238.1502,238.2514,131465,238.4658,1756904700000,1396,None,2025-09-03 13:05:00+00:00,2025-09-03 09:05:00-04:00
2,238.2545,238.2991,237.6601,237.8000,46115,237.9372,1756905000000,1050,None,2025-09-03 13:10:00+00:00,2025-09-03 09:10:00-04:00
3,237.7000,237.7615,237.2600,237.4000,60088,237.5413,1756905300000,1134,None,2025-09-03 13:15:00+00:00,2025-09-03 09:15:00-04:00

In [51]:
px.line(data_frame=df,x="timestamp_et",y="close")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'timestamp_et=%{x}<br>close=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([Timestamp('2025-09-03 04:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 04:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 05:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 06:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 07:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 08:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 09:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 10:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 11:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 12:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 13:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 14:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 15:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 16:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 17:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 18:55:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:00:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:05:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:10:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:15:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:20:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:25:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:30:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:35:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:40:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:45:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:50:00-0400', tz='America/New_York'),
                          Timestamp('2025-09-03 19:55:00-0400', tz='America/New_York')],
                         dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('KVyPwvV4bUCuR+F6FHZtQFyPwvUofG' ... 'UoXI/CbUBSuB6F68FtQE3zjlN0xG1A'),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'timestamp_et'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'close'}}}
})